version: '3.3'
 
services:

  eureka:
    build: ./eureka
    environment:
      server-port: "8761"
      eureka.client.serviceUrl.defaultZone: "http://eureka:8761/eureka/"
    tty: false
    ports:
      - "8761:8761"
      
  zuul:
    build: ./zuul
    environment:
      eureka.client.serviceUrl.defaultZone: "http://eureka:8761/eureka/"
      eureka.instance.preferIpAddress: "true"
    ports:
      - "8762:8762"
    depends_on:
      - "eureka"
    links:
      - eureka

  artemis:
    image: vromero/activemq-artemis:latest-alpine
    container_name: activemq
    environment:
      ARTEMIS_USERNAME: banka
      ARTEMIS_PASSWORD: banka1234
    ports:
      - "61616:61616/tcp"
      
  email-servis:
    build: ./mail-service
    environment:
      spring.mail.username: "email"
      spring.mail.password: "password"
    ports:
      - "8081:8081"
    links:
      - artemis
      - eureka
 
  db-user:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    volumes:
      - db-user:/var/lib/postgresql/data

  db-berza:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    volumes:
      - db-berza:/var/lib/postgresql/data

  db-influx:
    image: influxdb:2.1.1
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: raf
      DOCKER_INFLUXDB_INIT_PASSWORD: 12345678
      DOCKER_INFLUXDB_INIT_ORG: raf
      DOCKER_INFLUXDB_INIT_BUCKET: stocks
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mytoken
    ports:
      - "8086:8086"
    volumes:
      - influx-data:/var/lib/influxdb2
      - influx-config:/etc/influxdb2

  influx-scrapper:
    build: ./InfluxScrapper
    ports:
      - "8000:80"
    links:
      - db-influx
    depends_on:
      - db-influx

  korisnicki-servis:
    build: ./user-service
    environment:
      spring.datasource.hikari.jdbcUrl: jdbc:postgresql://db-user:5432/postgres
      spring.application.name: user-service
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
      eureka.instance.preferIpAddress: "true"
    ports:
      - "8080:8080"
    links:
      - db-user
      - artemis
      - eureka

  berza:
    build: ./berza
    environment:
      spring.datasource.hikari.jdbcUrl: jdbc:postgresql://db-berza:5432/postgres
      spring.application.name: berza
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
      eureka.instance.preferIpAddress: "true"
    ports:
      - "8082:8082"
    links:
      - db-berza
      - eureka

volumes:
  db-user:
  db-berza:
  influx-data:
  influx-config:
