server:
  port: 8762

spring:
  application:
    name: zuul-server


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceurl:
    defaultzone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"


# Hardcode service
#
#zuul:
# routes:
#  my-service:
#   path: /my-service/**
#   url: http://localhost:8080/

# Expose Headers
zuul:
  sensitiveHeaders: Cookie,Set-Cookie

ribbon:
  ReadTimeout: 60000
