name: User service
on:
  push:
    branches:
      - '**' # matchuj sve brancheve, posto dosta koristimo feature brancheve (po defaultu je samo master)
    paths:
      - 'pom.xml'
      - 'user-service/**'
      - '.github/workflows/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'pom.xml'
      - 'user-service/**'
      - '.github/workflows/**'
jobs:
  build:
    name: Build User service
    runs-on: ubuntu-latest
    steps:
      - uses: RAF-SI-2021/sonar-cloud-prep@v0.0.1
        with:
          java-version: 17
      - name: "[User Service] Build and analyze"
        working-directory: ./user-service
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_USER_SERVICE }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=rs.edu.raf.banka:user_service -Dsonar.projectName="Banka_User_Service" sonar:sonar -Pcoverage
